// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlkbnvfs0KYE1VeprXSxcPs6DJkhJOAVk',
    appId: '1:337470955661:web:a79a4438dfc9c540a0c2c4',
    messagingSenderId: '337470955661',
    projectId: 'todo-task-app-ccb0e',
    authDomain: 'todo-task-app-ccb0e.firebaseapp.com',
    storageBucket: 'todo-task-app-ccb0e.appspot.com',
    measurementId: 'G-G6SM95FRHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKDUkIv2wwvbdWoP59ZN3CXJi7zqwRKgI',
    appId: '1:337470955661:android:75082fa367a4ae78a0c2c4',
    messagingSenderId: '337470955661',
    projectId: 'todo-task-app-ccb0e',
    storageBucket: 'todo-task-app-ccb0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChSlPaADGugrC74HzLCYKj6JHH1MzPH3A',
    appId: '1:337470955661:ios:b12ea45218b9f687a0c2c4',
    messagingSenderId: '337470955661',
    projectId: 'todo-task-app-ccb0e',
    storageBucket: 'todo-task-app-ccb0e.appspot.com',
    iosBundleId: 'com.example.todoTaskApp',
  );
}
